(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (>= a 0))
(assert (>= b 0))
(assert (>= c 0))
(assert (= (* a b c) 1))
(assert (not (<= (+ (pow (+ 1 (* 8 a)) (/ -1 2)) (pow (+ 1 (* 8 b)) (/ -1 2)) (pow (+ 1 (* 8 c)) (/ -1 2))) 2)))
(check-sat)
(get-model)
(exit)