(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (<= (+ (^ a 2) (^ b 2) (^ c 2) (* a b) (* b c) (* c a)) 2))
(assert (not (<= 6 (+ (* 2 (+ (* a b) 1) (^ (^ (+ a b) 2) -1)) (* 2 (+ (* b c) 1) (^ (^ (+ b c) 2) -1)) (* 2 (+ (* c a) 1) (^ (^ (+ c a) 2) -1))))))
(check-sat)
(get-model)
(exit)