(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (> (+ a b (* -1 c)) 0))
(assert (> (+ a c (* -1 b)) 0))
(assert (> (+ b c (* -1 a)) 0))
(assert (not (<= (+ (^ (+ a b (* -1 c)) (/ 1 2)) (^ (+ b c (* -1 a)) (/ 1 2)) (^ (+ c a (* -1 b)) (/ 1 2))) (+ (^ a (/ 1 2)) (^ b (/ 1 2)) (^ c (/ 1 2))))))
(check-sat)
(get-model)
(exit)