(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (+ (* 8 (^ (* a b c) (* 1 (^ 3 -1)))) (^ (* (+ (^ a 3) (^ b 3) (^ c 3)) (^ 3 -1)) (* 1 (^ 3 -1)))) (* 3 (+ a b c)))))
(check-sat)
(get-model)
(exit)