(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (* 3 (^ 2 -1) (+ (^ a 2) (^ b 2) (^ c 2))) (+ (* (+ (^ a 3) (* 5 (^ b 3))) (^ (+ (* 3 a) b) -1)) (* (+ (^ b 3) (* 5 (^ c 3))) (^ (+ (* 3 b) c) -1)) (* (+ (^ c 3) (* 5 (^ a 3))) (^ (+ (* 3 c) a) -1))))))
(check-sat)
(get-model)
(exit)