(declare-const c Real)
(assert (> c 0))
(declare-const b Real)
(assert (> b 0))
(declare-const a Real)
(assert (> a 0))
(assert (not (<= (+ (* 8 (^ (* (* a b) c) (/ 1 3))) (/ (^ (+ (+ (^ a 3) (^ b 3)) (^ c 3)) (/ 1 3)) 3)) (* 3 (+ (+ a b) c)))))
(check-sat)
(get-model)
(exit)