(declare-const c Real)
(declare-const a Real)
(declare-const b Real)
(assert (<= (* (* a b) c) (/ 1 (* 3 (sqrt 3)))))
(assert (= (+ (+ (* a b) (* b c)) (* c a)) 1))
(assert (> c 0))
(assert (> b 0))
(assert (> a 0))
(assert (not (= (+ (+ (+ (* (* (* a b) c) (^ (+ (/ 1 c) (* 6 a)) (/ 1 3))) (* (* (* a b) c) (^ (+ (/ 1 b) (* 6 c)) (/ 1 3)))) (* (* (* a b) c) (^ (+ (/ 1 a) (* 6 b)) (/ 1 3)))) (- 1)) 0)))
(check-sat)
(get-model)
(exit)