(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (= (+ (+ a b) c) (sqrt 5)))
(assert (<= 0 a)) 
(assert (<= 0 b)) 
(assert (<= 0 c))
(assert (not (<= (* (* (+ (^ a 2) (- (^ b 2))) (+ (^ b 2) (- (^ c 2)))) (+ (^ c 2) (- (^ a 2)))) (sqrt 5))))
(check-sat)
(get-model)
(exit)