(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (>= a 0))
(assert (>= b 0))
(assert (>= c 0))
(assert (= (+ a b c) 1))
(assert (> (+ a b c (pow (* a b) (/ 1 2)) (pow (* a c) (/ 1 2)) (pow (* b c) (/ 1 2))) (+ (pow (* (+ a b) (+ a c)) (/ 1 2)) (pow (* (+ a b) (+ b c)) (/ 1 2)) (pow (* (+ a c) (+ b c)) (/ 1 2)))))
(check-sat)
(get-model)
(exit)