(declare-const c Real)
(assert (< 0.0 c))
(declare-const b Real)
(assert (< 0.0 b))
(declare-const a Real)
(assert (< 0.0 a))
(assert (distinct (- (/ 27.0 (* 2.0 (^ (+ (+ a b) c) 2))) (/ 27.0 (^ (+ (+ (^ (* a (+ b c)) (/ 1.0 2.0)) (^ (* b (+ c a)) (/ 1.0 2.0))) (^ (* c (+ a b)) (/ 1.0 2.0))) 2))) (- (/ 27.0 (* 2.0 (^ (+ (+ a b) c) 2))) (/ 27.0 (^ (+ (+ (sqrt (+ (* a b) (* a c))) (sqrt (+ (* a b) (* b c)))) (sqrt (+ (* a c) (* b c)))) 2)))))
(check-sat)
(get-model)