(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (>= a 0))
(assert (>= b 0))
(assert (>= c 0))
(assert (> (+ (* 3 (pow (+ (* (/ 2 3) (pow a 2)) (* (/ 2 3) (pow b 2)) (* (/ 2 3) (pow c 2)) (* (/ -1 3) a b) (* (/ -1 3) a c) (* (/ -1 3) b c)) 0.5)) (* 3 (pow 3 (/ 1 2)) (+ (pow (* a b) (/ 1 2)) (pow (* a c) (/ 1 2)) (pow (* b c) (/ 1 2))))) (+ (* 4 a) (* 4 b) (* 4 c))))
(check-sat)
(get-model)
(exit)