(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (>= a 0))
(assert (>= b 0))
(assert (>= c 0))
(assert (> (+ (pow (+ (pow a 2) (pow b 2) (* -1 a b)) (/ 1 2)) (pow (+ (pow a 2) (pow c 2) (* -1 a c)) (/ 1 2)) (pow (+ (pow b 2) (pow c 2) (* -1 b c)) (/ 1 2)) (* 3 (pow (* a b) (/ 1 2))) (* 3 (pow (* a c) (/ 1 2))) (* 3 (pow (* b c) (/ 1 2)))) (+ (* 4 a) (* 4 b) (* 4 c))))
(check-sat)
(get-model)
(exit)
