(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (>= a 0))
(assert (>= b 0))
(assert (>= c 0))
(assert (= a b))
(assert (= b 1))
(assert (= c 1))
(check-sat)
(get-model)
(exit)