(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (distinct (- 1.0 (* (sqrt (+ (+ a b) c)) (sqrt (/ (^ (+ (+ c b) a) 3) (+ (+ (* c (^ (sqrt (+ (+ (+ (^ a 3) (* (* (* 24.0 a) b) c)) (^ b 3)) (^ c 3))) 2)) (* b (^ (sqrt (+ (+ (+ (^ a 3) (* (* (* 24.0 a) b) c)) (^ b 3)) (^ c 3))) 2))) (* a (^ (sqrt (+ (+ (+ (^ a 3) (* (* (* 24.0 a) b) c)) (^ b 3)) (^ c 3))) 2))))))) (- 1.0 (* (sqrt (+ (+ (+ (/ (^ (+ (+ a b) c) 2) (^ a 3)) (* (* (* 24.0 a) b) c)) (^ b 3)) (^ c 3))) (sqrt (+ (+ a b) c))))))
(check-sat)
(get-model)