(declare-const b Real)
(declare-const c Real)
(declare-const a Real)
(assert (= (+ (+ a b) c) 1.0))
(assert (< 0.0 c))
(assert (< 0.0 b))
(assert (< 0.0 a))
(assert (distinct (- (+ (+ (+ (+ (+ a b) c) (sqrt (* a b))) (sqrt (* a c))) (sqrt (* b c))) (+ (+ (sqrt (* (+ a c) (+ b c))) (sqrt (* (+ a b) (+ b c)))) (sqrt (* (+ a b) (+ a c))))) (- (+ (+ (+ (+ (+ a b) c) (* (sqrt a) (sqrt b))) (* (sqrt a) (sqrt c))) (* (sqrt b) (sqrt c))) (+ (+ (* (sqrt (+ a b)) (sqrt (+ a c))) (* (sqrt (+ a b)) (sqrt (+ b c)))) (* (sqrt (+ a c)) (sqrt (+ b c)))))))
(check-sat)
(get-model)