(set-logic QF_NRA)
(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (= (* a b c) 1))
(assert (not (<= (* 1 (/ 1 3)) (+ (* 1 (/ 1 (* (^ a 5) (^ (+ b (* 2 c)) 2)))) (* 1 (/ 1 (* (^ b 5) (^ (+ c (* 2 a)) 2)))) (* 1 (/ 1 (* (^ c 5) (^ (+ a (* 2 b)) 2))))))))
(check-sat)
(get-model)
(exit)