(set-logic QF_NRA)
(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (<= 3 (+ a b c)))
(assert (= (+ a b c) (+ (* 1 (/ 1 a)) (* 1 (/ 1 b)) (* 1 (/ 1 c)))))
(assert (not (<= (+ (* 1 (/ 1 (^ (+ (* 2 a) b c) 2))) (* 1 (/ 1 (^ (+ a (* 2 b) c) 2))) (* 1 (/ 1 (^ (+ a b (* 2 c)) 2)))) (* 3 (/ 1 16)))))
(check-sat)
(get-model)
(exit)