(set-logic QF_NRAT)
(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (> (+ a b (* -1 c)) 0))
(assert (> (+ a c (* -1 b)) 0))
(assert (> (+ b c (* -1 a)) 0))
(assert (not (<= (+ (sqrt (+ a b (* (- 1) c))) (sqrt (+ b c (* (- 1) a))) (sqrt (+ c a (* (- 1) b)))) (+ (sqrt a) (sqrt b) (sqrt c)))))
(check-sat)
(get-model)
(exit)