(set-logic QF_NRA)
(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(declare-const x1 Real)
(declare-const x2 Real)
(declare-const y1 Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (= (^ x1 3) (* a b c)))
(assert (= (* y1 3) (+ (^ a 3) (^ b 3) (^ c 3))))
(assert (= (^ x2 3) y1))
(assert (not (<= (+ (* 8 x1) x2) (* 3 (+ a b c)))))
(check-sat)
(get-model)
(exit)