(set-logic QF_NRA)
(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (* 3 (/ 1 2) (+ (^ a 2) (^ b 2) (^ c 2))) (+ (* (+ (^ a 3) (* 5 (^ b 3))) (/ 1 (+ (* 3 a) b))) (* (+ (^ b 3) (* 5 (^ c 3))) (/ 1 (+ (* 3 b) c))) (* (+ (^ c 3) (* 5 (^ a 3))) (/ 1 (+ (* 3 c) a)))))))
(check-sat)
(get-model)
(exit)