(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (= (* a b c) 1))
(assert (not (<= (* 1 (pow 3 -1)) (+ (* 1 (pow (* (pow a 5) (pow (+ b (* 2 c)) 2)) -1)) (* 1 (pow (* (pow b 5) (pow (+ c (* 2 a)) 2)) -1)) (* 1 (pow (* (pow c 5) (pow (+ a (* 2 b)) 2)) -1))))))
(check-sat)
(get-model)
(exit)