(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (+ (* 8 (pow (* a b c) (* 1 (pow 3 -1)))) (* (pow (+ (pow a 3) (pow b 3) (pow c 3)) (* 1 (pow 3 -1))) (pow 3 -1))) (* 3 (+ a b c)))))
(check-sat)
(get-model)
(exit)