(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (+ (pow (+ a b (* -1 c)) (/ 1 2)) (pow (+ b c (* -1 a)) (/ 1 2)) (pow (+ c a (* -1 b)) (/ 1 2))) (+ (pow a (/ 1 2)) (pow b (/ 1 2)) (pow c (/ 1 2))))))
(check-sat)
(get-model)
(exit)