(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (= (+ a b c) 1))
(assert (not (<= (+ (* 1 (pow (+ a 2) -1)) (* 1 (pow (+ b 2) -1)) (* 1 (pow (+ c 2) -1))) (+ (* 1 (pow (+ (* 6 (pow (* a b) (/ 1 2))) c) -1)) (* 1 (pow (+ (* 6 (pow (* b c) (/ 1 2))) a) -1)) (* 1 (pow (+ (* 6 (pow (* c a) (/ 1 2))) b) -1))))))
(check-sat)
(get-model)
(exit)