(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (* 27 (pow (* 2 (pow (+ a b c) 2)) -1)) (+ (* 1 (pow (* a (+ b c)) -1)) (* 1 (pow (* b (+ c a)) -1)) (* 1 (pow (* c (+ a b)) -1))))))
(check-sat)
(get-model)
(exit)