(declare-const a Real)
(declare-const b Real)
(declare-const c Real)
(assert (> a 0))
(assert (> b 0))
(assert (> c 0))
(assert (not (<= (* 3 (pow 2 -1) (+ (pow a 2) (pow b 2) (pow c 2))) (+ (* (+ (pow a 3) (* 5 (pow b 3))) (pow (+ (* 3 a) b) -1)) (* (+ (pow b 3) (* 5 (pow c 3))) (pow (+ (* 3 b) c) -1)) (* (+ (pow c 3) (* 5 (pow a 3))) (pow (+ (* 3 c) a) -1))))))
(check-sat)
(get-model)
(exit)