(declare-const b Real)
(assert (> (+ 1 (- b)) 0))
(assert (> b 0))
(declare-const a Real)
(assert (> (+ 1 (- a)) 0))
(assert (> a 0))
(assert (not (= (+ 0 (- (+ (* a (log (/ a b))) (* (+ 1 (- a)) (log (/ (+ 1 (- a)) (+ 1 (- b)))))))) (+ (* a (log (/ b a))) (* (+ 1 (- a)) (log (/ (+ 1 (- b)) (+ 1 (- a)))))))))
(check-sat)
(get-model)